name: Rote
package: cloud.lazycat.app.rote
version: 1.2.2
min_os_version: 1.3.8
description: "A personal note repository that looks different"
license: MIT
homepage: https://github.com/Rabithua/Rote
author: Rabithua

application:
  subdomain: rote
  public_path:
    - /
  upstreams:
    - location: /
      domain_prefix: backend
      backend: http://rote-backend:3000/

    - location: /
      backend: http://rote-frontend:80/

services:
  rote-postgres:
    image: registry.lazycat.cloud/czyt/library/postgres:e0540de354c564d5
    environment:
      - POSTGRES_USER=rote
      - POSTGRES_PASSWORD=rote_password_123
      - POSTGRES_DB=rote
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U rote -d rote
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    binds:
      - /lzcapp/var/postgres:/var/lib/postgresql/data

  rote-backend:
    # rabithua/rote-backend:latest
    image: registry.lazycat.cloud/czyt/rabithua/rote-backend:ba2fc6297689d7fb
    environment:
      - POSTGRESQL_URL=postgresql://rote:rote_password_123@rote-postgres:5432/rote
    depends_on:
      - rote-postgres
    command: sh -c 'sleep 15 && bun run dist/scripts/runMigrations.js && bun run dist/server.js'

  rote-frontend:
    # rabithua/rote-frontend:latest
    image: registry.lazycat.cloud/czyt/rabithua/rote-frontend:12c435338d095965
    environment:
      - VITE_API_BASE=https://backend-{{.S.AppDomain}}
    depends_on:
      - rote-backend

locales:
  en:
    name: "Rote"
    description: "A personal note repository that looks different"
  zh:
    name: "Rote"
    description: "一个与众不同的个人笔记仓库"
